# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install python 3.8.1
      uses: gabrielfalcao/pyenv-action@v5
      with:
        default: 3.8.1
        command: pip install -U pip  # upgrade pip after installing python

    - name: Create virtualenv for python 3.8.1
      run: pyenv local 3.8.1

    - name: Install BlockDiag
      run: make installBlockDiag

    - name: Test BlockDiag
      run: make testBlockDiag

    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12

    - name: Install Java dependencies
      run: make installLocalDependencies

    - name: Build Java server
      run: make buildServer

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: 19.03.8
        docker_channel: stable

    - name: Build container images
      run: make buildDockerImages
